### ISSUE TITLE
Close stream gracefully

### ISSUE THREAD

**Issue by stsdc** [TurtleRover/tcs#25]

**Comment by SzymonDzw** [comment]
This bug is very annoying for the customers. You don't really see the streaming is open on another device and I have constant complains on streaming not working.

**Comment by Mictronics** [comment]
You should raise a screen message when streaming is busy. However, I see the problem on uv4l side since WebRTC seems not to detect a lost connection nor is there a timeout. And this is where the error mostly occur. Got the same experience on my side.

**Comment by stsdc** [comment]
@Mictronics Agree. We will try to replace uv4l with gstreamer.

**Comment by Mictronics** [comment]
@stsdc Got feedback from uv4l developer. He is pointing to https://www.linux-projects.org/webrtc-signalling/ especially the hangup message. Doesn't work however, because one can not open a new websocket to WebRTC server while still streaming. So no way to send a hangup to an old connection. He is rar on answer to my questions, though.

**Comment by stsdc** [comment]
@Mictronics well, there are plenty of issues with UV4L. If You will get any useful info from the developer let me know. I hope we manage to run gstreamer + custom signalling server, so we will have full control over video streaming in the future.

**Comment by Mictronics** [comment]
@stsdc After some back and forth I got message from the uv4l developer that this connection loss problem will be fixed in next release. Seems he finally understood what the real problem is/was. Let's see...

**Comment by Mictronics** [comment]
@stsdc Good news! With the latest uv4l release the webrtc connection timeout works finally. A connection loss, e.g. disconnect LAN or cut Wifi, will now reset webrtc and one can reconnect immediately.

Only one important thing:
The option `server-option = --connection-timeout=10` in `/etc/uv4l/uv4l-uvc.conf` must be set to a minimum of at least 7 seconds or more. I found that with lower values, e.g. 5 seconds, the connection will run into this timeout right after connection open. Obviously some internal delays are having the uv4l websocket server send ping's only after several seconds.

`server-option = --connection-timeout=0` will disable connection timeout and the socket stays open even after connection loss (old behavior).
