### ISSUE TITLE
0.14.0 - Add description to 'menu-about'

### ISSUE THREAD

**Issue by SzymonDzw** [TurtleRover/tcs#56]
In menu - about add:
Header: Welcome to Turtle Rover Control Interface
Paragraph: Please refer to docs.turtlerover.com to know more about the control options and the Rover maintenance. Feel free to contact us if you have any issue. We're constantly improving the UI, but it's still a long way to go. We'd love to have you participate in the project and get any feedback!
[align to right] - Turtle Team

contact@turtlerover.com
www.turtlerover.com

**Comment by stsdc** [comment]
Blocked by: https://github.com/TurtleRover/tcs/issues/58
Temporary solution on its way.
